"""empty message

Revision ID: 863ceb65c8c1
Revises: 
Create Date: 2022-01-17 22:47:07.251305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863ceb65c8c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=125), nullable=False),
    sa.Column('productType', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=125), nullable=False),
    sa.Column('score', sa.Float(precision=2), nullable=True),
    sa.Column('scoreLevel', sa.Integer(), nullable=True),
    sa.Column('learnerCount', sa.Integer(), nullable=True),
    sa.Column('couponPrice', sa.Float(precision=2), nullable=True),
    sa.Column('lessonCount', sa.Integer(), nullable=True),
    sa.Column('originalPrice', sa.Float(precision=2), nullable=True),
    sa.Column('discountPrice', sa.Float(precision=2), nullable=True),
    sa.Column('vipPrice', sa.Float(precision=2), nullable=True),
    sa.Column('imgUrl', sa.String(length=125), nullable=True),
    sa.Column('bigImgUrl', sa.String(length=125), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('productName', sa.String(length=125), nullable=False),
    sa.Column('learnerCount', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['course.productId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('course')
    # ### end Alembic commands ###
