"""add hobby

Revision ID: 2709b27c96ef
Revises: e8beb94ce753
Create Date: 2022-01-15 23:08:38.307932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2709b27c96ef'
down_revision = 'e8beb94ce753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('hobby', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hobby')
    op.drop_column('user', 'gender')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
